spring:
  datasource:
    url: jdbc:mysql://localhost:1406/
    username: root
    password: root

mysql:
  statsDbName: supstats
  statsTableName: stats_511
  chunkSize: 1000

kafka:
  sinkTopic: dbTopic2
